import realHair from "../images/real_hair.png";
import realKhabib from "../images/realKhabib.jpg";
import khabib from "../images/khabib.png";
import vicky from "../images/vickyKaushal.jpg";
import pikachu from "../images/Pikachu.jpg";
import baby from "../images/baby2.jpg";
import moralis from "../images/moralis.png";
import moralisLogo from "../images/moralisLogo.png";
import moralisScene from "../images/moralisScene.png";
import jam from "../images/jam.png";
import jamLogo from "../images/jamLogo.png";
import jamScene from "../images/jamScene.png";

export const movies = [
  {
    Movie: "",
    Thumnbnail: realHair,
    Scene: khabib,
    Logo: "",
    Name: "Realistic Hair",
    Description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    Genre: "Art, Tutorial",
    Actors: "Edward Asner, Jordan Nagai",
    Year: "2009",
    Duration: "1h 36m",
  },
  {
    Movie: "https://ipfs.moralis.io:2053/ipfs/QmNtxfy9Mk8qLsdGnraHGk5XDim8ayR93krM24ETJEd2bG/media/0",
    Thumnbnail: realKhabib,
    Scene: realKhabib,
    Logo: "",
    Name: "Khabib Nurmagomedov",
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    Genre: "Art, Tutorial",
    Actors: "Tom Holland, Zendeya",
    Year: "2017",
    Duration: "2h 13min",
  },
  {
    Movie: "",
    Thumnbnail: vicky,
    Scene: vicky,
    Logo: "",
    Name: "Vicky Kaushal",
    Description: "",
    Genre: "",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "https://ipfs.moralis.io:2053/ipfs/QmWWnyCZwh8RVnamjeLhGmpYM2C3oDr3FzF7zgv5ur24z5/media/0",
    Thumnbnail: moralis,
    Scene: moralisScene,
    Logo: moralisLogo,
    Name: "Moralis Rap",
    Description: "Moralis serverless Web3 Dapps, is a beautiful music video that tells a touching story of how anyone can become a Web3 developer if they put their trust in the hands of the musically gifted team at Moralis. ",
    Genre: "Music Video",
    Actors: "Ivan Liljeqvist, Filip Martinsson, CTO Larsson",
    Year: "2021",
    Duration: "1min 2sec",
  },
  {
    Movie: "",
    Thumnbnail: pikachu,
    Scene: pikachu,
    Logo: "",
    Name: "Detective Pikachu",
    Description: "",
    Genre: "Art, Tutorial",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumnbnail: baby,
    Scene: baby,
    Logo: "",
    Name: "Realistic Baby Drwaing",
    Description: "",
    Genre: "Art, Tutorial",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "https://ipfs.moralis.io:2053/ipfs/QmSi84pJTjBXmXREN8NMRuRnK9oobYb8QcPZsXUj3GZr12/media/0",
    Thumnbnail: jam,
    Scene: jamScene,
    Logo: jamLogo,
    Name: "Jam Doughnut",
    Description: "In this masterpiece a wild Jay, endulges in flavorful jam doughnut. Be warned, this video is most certainly going to leave you craving for some sweets.",
    Genre: "Silent Mukbang",
    Actors: "Jay",
    Year: "2022",
    Duration: "1min 5sec",
  },
  {
    Movie: "",
    Thumnbnail: realHair,
    Scene: realHair,
    Logo: "",
    Name: "Khabib Nurmagomendov",
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    Genre: "Art, Tutorial",
    Actors: "Edward Asner, Jordan Nagai",
    Year: "2009",
    Duration: "1h 36m",
  },
  {
    Movie: "https://ipfs.moralis.io:2053/ipfs/QmNtxfy9Mk8qLsdGnraHGk5XDim8ayR93krM24ETJEd2bG/media/0",
    Thumnbnail: realKhabib,
    Scene: realKhabib,
    Logo: "",
    Name: "Khabib Nurmagomedov",
    Description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    Genre: "Art, Tutorial",
    Actors: "Tom Holland, Zendeya",
    Year: "2017",
    Duration: "2h 13min",
  },
  {
    Movie: "https://ipfs.moralis.io:2053/ipfs/QmWWnyCZwh8RVnamjeLhGmpYM2C3oDr3FzF7zgv5ur24z5/media/0",
    Thumnbnail: moralis,
    Scene: moralisScene,
    Logo: moralisLogo,
    Name: "Moralis Rap",
    Description: "Moralis serverless Web3 Dapps, is a beautiful music video that tells a touching story of how anyone can become a Web3 developer if they put their trust in the hands of the musically gifted team at Moralis. ",
    Genre: "Music Video",
    Actors: "Ivan Liljeqvist, Filip Martinsson, CTO Larsson",
    Year: "2021",
    Duration: "1min 2sec",
  },
  {
    Movie: "",
    Thumnbnail: pikachu,
    Scene: pikachu,
    Logo: "",
    Name: "Detective Pikachu",
    Description: "",
    Genre: "Art, Tutorial",
    Actors: "",
    Year: "",
    Duration: "",
  },
  {
    Movie: "",
    Thumnbnail: baby,
    Scene: baby,
    Logo: "",
    Name: "Realistic Baby Drawing",
    Description: "",
    Genre: "Art, Tutorial",
    Actors: "",
    Year: "",
    Duration: "",
  },
];